---
development:
  cloud_name: hoxr8ugj3
  api_key: '975985594182779'
  api_secret: D5kXxlpctIaQdpqLn50lqepzsM4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= RAILS_ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= RAILS_ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= RAILS_ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hoxr8ugj3
  api_key: '975985594182779'
  api_secret: D5kXxlpctIaQdpqLn50lqepzsM4
  enhance_image_tag: true
  static_image_support: false
