development:
  cloud_name: hfqbomylo
  api_key: '183281716346692'
  api_secret: uCgutFjCvq2O1IRqFwxWvhI1AFk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hfqbomylo
  api_key: '183281716346692'
  api_secret: uCgutFjCvq2O1IRqFwxWvhI1AFk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hfqbomylo
  api_key: '183281716346692'
  api_secret: uCgutFjCvq2O1IRqFwxWvhI1AFk
  enhance_image_tag: true
  static_image_support: false